routes/web.php
<?php
Route::get('/', function () { return redirect('/admin'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Social Login Routes..
Route::get('login/{driver}', 'Auth\LoginController@redirectToSocial')->name('auth.login.social');
Route::get('{driver}/callback', 'Auth\LoginController@handleSocialCallback')->name('auth.login.social_callback');


// client part of authenication
Route::group(['middleware' => ['auth']], function(){

    Route::get('/order', 'OrderController@index');
    // Part of fillind address and order product with pasion
    Route::get('/order', 'OrderController@index');
    Route::post('/order', 'OrderController@order');
    Route::get('/myorders', 'OrderController@showOrders');

    Route::post('/order/confirm', 'OrderController@confirmOrder');
    Route::get('/order/delete/{id}', 'OrderController@destroy');
    Route::get('/cart', 'OrderController@getOrderCart');

    Route::get('/order/custom/product','OrderController@customPizza');
    Route::post('/order/store/custom', 'OrderController@storeOrder');
     // End of orders

    // Part of products
    Route::get('/product', 'ProductsController@index');
    Route::get('/product/show/{id}', 'ProductsController@show');

    //ends of products

    //addresses
    Route::get('/address', 'AddressController@index');
    Route::get('/address/create', 'AddressController@create');
    Route::post('/address/store', 'AddressController@add');
    Route::get('/address/delete/{id}', 'AddressController@destroy');
});

// admin part of authentication
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', function () {
            return redirect('/admin/home');
    });

    Route::get('/', 'HomeController@index');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::get('internal_notifications/read', 'InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('attributes', 'Admin\AttributesController');
    Route::post('attributes_mass_destroy', ['uses' => 'Admin\AttributesController@massDestroy', 'as' => 'attributes.mass_destroy']);
    Route::resource('attribute_items', 'Admin\AttributeItemsController');
    Route::post('attribute_items_mass_destroy', ['uses' => 'Admin\AttributeItemsController@massDestroy', 'as' => 'attribute_items.mass_destroy']);
    Route::resource('products', 'Admin\ProductsController');
    Route::post('products_mass_destroy', ['uses' => 'Admin\ProductsController@massDestroy', 'as' => 'products.mass_destroy']);
    Route::resource('orders', 'Admin\OrdersController');
    Route::post('orders_mass_destroy', ['uses' => 'Admin\OrdersController@massDestroy', 'as' => 'orders.mass_destroy']);
    Route::resource('addresses', 'Admin\AddressesController');
    Route::post('addresses_mass_destroy', ['uses' => 'Admin\AddressesController@massDestroy', 'as' => 'addresses.mass_destroy']);
    Route::resource('orderitems', 'Admin\OrderitemsController');
    Route::post('orderitems_mass_destroy', ['uses' => 'Admin\OrderitemsController@massDestroy', 'as' => 'orderitems.mass_destroy']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'MessengerController');
});

app/Attribute.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Attribute
 *
 * @package App
 * @property string $name
 * @property string $slug
*/
class Attribute extends Model
{
    protected $fillable = ['name', 'slug'];

    public static function boot()
    {
        parent::boot();

        Attribute::observe(new \App\Observers\UserActionsObserver);
    }

    // public function getNameAttribute($value)
    // {
    //
    //     $value = explode(' ', $value);
    //     return ucfirst($value[0]);
    // }

}

app/Http/Controllers/Admin/AttributesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Attribute;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreAttributesRequest;
use App\Http\Requests\Admin\UpdateAttributesRequest;
use Yajra\Datatables\Datatables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class AttributesController extends Controller
{
    /**
     * Display a listing of Attribute.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('attribute_access')) {
            return abort(401);
        }

        $attributes = Attribute::all();

        return view('admin.attributes.index', compact('attributes'));
    }

    /**
     * Show the form for creating new Attribute.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('attribute_create')) {
            return abort(401);
        }
        return view('admin.attributes.create');
    }

    /**
     * Store a newly created Attribute in storage.
     *
     * @param  \App\Http\Requests\StoreAttributesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAttributesRequest $request)
    {
        if (! Gate::allows('attribute_create')) {
            return abort(401);
        }
        $attribute = Attribute::create($request->all());



        return redirect()->route('admin.attributes.index');
    }


    /**
     * Show the form for editing Attribute.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('attribute_edit')) {
            return abort(401);
        }
        $attribute = Attribute::findOrFail($id);

        return view('admin.attributes.edit', compact('attribute'));
    }

    /**
     * Update Attribute in storage.
     *
     * @param  \App\Http\Requests\UpdateAttributesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAttributesRequest $request, $id)
    {
        if (! Gate::allows('attribute_edit')) {
            return abort(401);
        }
        $attribute = Attribute::findOrFail($id);
        $attribute->update($request->all());



        return redirect()->route('admin.attributes.index');
    }


    /**
     * Display Attribute.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('attribute_view')) {
            return abort(401);
        }
        $attribute_items = \App\AttributeItem::whereHas('attribute',
                    function ($query) use ($id) {
                        $query->where('id', $id);
                    })->get();

        $attribute = Attribute::findOrFail($id);

        return view('admin.attributes.show', compact('attribute', 'attribute_items'));
    }


    /**
     * Remove Attribute from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('attribute_delete')) {
            return abort(401);
        }
        $attribute = Attribute::findOrFail($id);
        $attribute->delete();

        return redirect()->route('admin.attributes.index');
    }

    /**
     * Delete all selected Attribute at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('attribute_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Attribute::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

app/Http/Controllers/Api/V1/AttributesController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Attribute;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreAttributesRequest;
use App\Http\Requests\Admin\UpdateAttributesRequest;
use Yajra\Datatables\Datatables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class AttributesController extends Controller
{
    public function index()
    {
        return Attribute::all();
    }

    public function show($id)
    {
        return Attribute::findOrFail($id);
    }

    public function update(UpdateAttributesRequest $request, $id)
    {
        $attribute = Attribute::findOrFail($id);
        $attribute->update($request->all());
        

        return $attribute;
    }

    public function store(StoreAttributesRequest $request)
    {
        $attribute = Attribute::create($request->all());
        

        return $attribute;
    }

    public function destroy($id)
    {
        $attribute = Attribute::findOrFail($id);
        $attribute->delete();
        return '';
    }
}

resources/views/admin/attributes/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.attributes.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.attributes.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('slug', 'Slug*', ['class' => 'control-label']) !!}
                    {!! Form::text('slug', old('slug'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('slug'))
                        <p class="help-block">
                            {{ $errors->first('slug') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/attributes/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.attributes.title')</h3>
    
    {!! Form::model($attribute, ['method' => 'PUT', 'route' => ['admin.attributes.update', $attribute->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('slug', 'Slug*', ['class' => 'control-label']) !!}
                    {!! Form::text('slug', old('slug'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('slug'))
                        <p class="help-block">
                            {{ $errors->first('slug') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/attributes/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.attributes.title')</h3>
    @can('attribute_create')
    <p>
        <a href="{{ route('admin.attributes.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($attributes) > 0 ? 'datatable' : '' }} @can('attribute_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('attribute_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.attributes.fields.name')</th>
                        <th>@lang('quickadmin.attributes.fields.slug')</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($attributes) > 0)
                        @foreach ($attributes as $attribute)
                            <tr data-entry-id="{{ $attribute->id }}">
                                @can('attribute_delete')
                                    <td></td>
                                @endcan

                                <td>{{ $attribute->name }}</td>
                                <td>{{ $attribute->slug }}</td>
                                <td>
                                    @can('attribute_view')
                                    <a href="{{ route('admin.attributes.show',[$attribute->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('attribute_edit')
                                    <a href="{{ route('admin.attributes.edit',[$attribute->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('attribute_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.attributes.destroy', $attribute->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('attribute_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.attributes.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/attributes/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.attributes.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.attributes.fields.name')</th>
                            <td>{{ $attribute->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.attributes.fields.slug')</th>
                            <td>{{ $attribute->slug }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#attributeitems" aria-controls="attributeitems" role="tab" data-toggle="tab">Attribute items</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="attributeitems">
<table class="table table-bordered table-striped {{ count($attribute_items) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('quickadmin.attribute-items.fields.attribute')</th>
                        <th>@lang('quickadmin.attribute-items.fields.name')</th>
                        <th>@lang('quickadmin.attribute-items.fields.value')</th>
                        <th>@lang('quickadmin.attribute-items.fields.photo')</th>
                        <th>&nbsp;</th>
        </tr>
    </thead>

    <tbody>
        @if (count($attribute_items) > 0)
            @foreach ($attribute_items as $attribute_item)
                <tr data-entry-id="{{ $attribute_item->id }}">
                    <td>
                                    @foreach ($attribute_item->attribute as $singleAttribute)
                                        <span class="label label-info label-many">{{ $singleAttribute->name }}</span>
                                    @endforeach
                                </td>
                                <td>{{ $attribute_item->name }}</td>
                                <td>{{ $attribute_item->value }}</td>
                                <td>@if($attribute_item->photo)<a href="{{ asset('uploads/' . $attribute_item->photo) }}" target="_blank"><img src="{{ asset('uploads/thumb/' . $attribute_item->photo) }}"/></a>@endif</td>
                                <td>
                                    @can('attribute_item_view')
                                    <a href="{{ route('admin.attribute_items.show',[$attribute_item->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('attribute_item_edit')
                                    <a href="{{ route('admin.attribute_items.edit',[$attribute_item->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('attribute_item_delete')
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.attribute_items.destroy', $attribute_item->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="8">@lang('quickadmin.qa_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.attributes.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop